package correlation

const (
	ENV_MAX_CORRELATIONS    = "INSTRUMENTATION_MAX_CORRELATIONS"
	ENV_CORRELATION_MAX_AGE = "INSTRUMENTATION_CORRELATION_MAX_AGE"
	ENV_CLEANUP_INTERVAL    = "INSTRUMENTATION_CLEANUP_INTERVAL"
	ENV_DEBUG_CORRELATION   = "INSTRUMENTATION_DEBUG_CORRELATION"
)

const (
	DefaultMaxCorrelations   = 100000
	DefaultCorrelationMaxAge = 50000
	DefaultCleanupInterval   = 10000
)
